/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:63bead62-032e-446c-8f46-d8bcd5a9fda4",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_Qr976cpCZ",
    "aws_user_pools_web_client_id": "4k3egl58bcg08hfphis8d6ctgt",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://gcd7uvasgfgflmgzwgwzhcjucm.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
